### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by GideonWolfe** [kressh/nextcloud-news-updater#1]
`019-11-23 19:39:10,408 - Nextcloud News Updater - ERROR - <urlopen error [Errno 99] Address not available>: Trying again in 30 seconds`

I am using the correct URL, my username, and a unique app password created because I use 2FA. The nextcloud instance is also hosted in another docker container. Is that an issue?

**Comment by bsedin** [comment]
It shouldn't be.

I use nextcloud:17-fpm-alpine docker image with nginx and news updater works fine through https:

```
NEXTCLOUD_URL: https://mynextcloud.com
NEXTCLOUD_ADMIN_USER: adminuser
NEXTCLOUD_ADMIN_PASSWORD: adminpassword
```

Does your nextcloud instance available from outside? If you wan't to connect through docker network, you have to link containers or use same docker network. Maybe that?

**Comment by GideonWolfe** [comment]
Yes, the instance is available from the outside. I tried mounting my nextcloud volume, but the command running inside the container still uses the username/password.

I put everything on the same network, (I use the traefik reverse proxy) and now I am seeing the error:
` Nextcloud News Updater - ERROR - <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>: Trying again in 30 seconds`

This might be the app rejecting the default traefik cert, which is replaced by my real ssl cert after a second or two. I'm not sure because the error does not repeat and there are no other logs. No idea if it's working.

**Comment by bsedin** [comment]
Looks like it should work after retry if cert and credentials is valid.

I checked news-updater docs (https://github.com/nextcloud/news-updater#usage), you can set log level to info to see whats going on, or just add HN feed and check if there is any new entries in a couple hours.
